#!/bin/bash

make -s solver

dataFolder="data"
resultsFolder="results"
nIterations=50

echo -e "Running all configurations in folder '$dataFolder'"
for file in $dataFolder/*
do
	scripts/run "$file" $nIterations
done